### ISSUE TITLE
Prior Encounters dont show any details

### ISSUE THREAD

**Issue by donrukanga1** [UNFPAInnovation/GetIn_Mobile#23]
When u select prior Encounter(Girls mapped by you) it shows no details of the mapped girl when you select her from the list.

**Comment by ewinkler** [comment]
Line 59, PatientRunnerFragment. Set showCompleteConfirmation to true.

**Comment by ewinkler** [comment]
Maping form decorates the patient object. Is not related to the Encounter records. Will need a Fragment/DialogFragment that shows a patient summary. 
1. Possibly link to PatientList
2. Maybe short click view summary/long click edit
