### ISSUE TITLE
The patient record issue(showing all patient records)

### ISSUE THREAD

**Issue by donrukanga1** [UNFPAInnovation/GetIn_Mobile#35]
Miidwife needs to view All previous encounters she has had with the girl plus those of the VHT

**Comment by ewinkler** [comment]
Please specify where in the workflow this needs to happen.

**Comment by donrukanga1** [comment]
Penninah said it should occur just before the appointment note is triggered. That is in the Upcoming appointments.
So she should view and them take more records
