### ISSUE TITLE
The setting of the Appointment date during followup hasnt been implemented yet

### ISSUE THREAD

**Issue by donrukanga1** [UNFPAInnovation/GetIn_Mobile#36]
The next appointment date set during followup and ANC appointment is not being captured as a task

**Comment by ewinkler** [comment]
Read the input of the "Next Appointment" Element in the "Follow up" Procedure and generate the Task at the end of the Encounter probably in the VHT MainActivity.onActivity result method.

**Comment by ewinkler** [comment]
Remove redundant field in Midwife mapping form as in #45.

**Comment by donrukanga1** [comment]
ON the issue of the setting tasks from the follow up note, we could actually just change the concept to ANC visit rather than the Next Appointment and then it could be added everytime its set.

**Comment by ewinkler** [comment]
We need to discuss this further. We can't just change the concept to ANC_VISIT in the appointment_note or follow_up form because the visit notes generate Observation records per element in the form whereas the mapping forms set the Patient object fields.

**Comment by ewinkler** [comment]
The anc_visit is reading from the observations but there seem to be some lingering references to a "next appointment" concept. Which procedure resources do we need to update?

**Comment by ewinkler** [comment]
Can we close this?

**Comment by donrukanga1** [comment]
one queery i have before we close is ; Do we need to add the Next Appointment field in the followup note?Or we can leave it as ANC_visit

**Comment by ewinkler** [comment]
ANC visit is fine. Just have to be consistent with how we use it on both client and server.

**Comment by donrukanga1** [comment]
The Task is created but it shows the wrong date. Eg i set 04 July 2017 and it keeps returning 11 April 2017 for all the tests am doing
