### ISSUE TITLE
Synching girls of a particular location to the VHT's device of that location incase she is mapped from the Health Center

### ISSUE THREAD

**Issue by donrukanga1** [UNFPAInnovation/GetIn_Mobile#38]
VHT needs to followup girls in her Village even when she didnot neccesarily map her

**Comment by ewinkler** [comment]
'village' field needs to be implemented as a Location object and not as a String. We reimplemented the 'location' field as a String to hold the extended GPS data but this is fundamentally different than trying to use a foreign key relationship to an object like a 'village'.

**Comment by ewinkler** [comment]
Updated the query passed to the synch. Need to doublecheck the server returns as expected.

**Comment by donrukanga1** [comment]
I still see a number of girls with diffrent villages in the VHT app. Did we assign the VHT app to a specific location yet? 
Otherwise dont know how i  can test this issue
