### ISSUE TITLE
Action Button in VHT FollowUp note not working

### ISSUE THREAD

**Issue by donrukanga1** [UNFPAInnovation/GetIn_Mobile#39]

**Comment by ewinkler** [comment]
I added a log line to capture the Intent string. See MainActivity-line 644, commit [20fbdf97e5ec1d7900244edd1fae5b236866964d](https://github.com/UNFPAInnovation/GetIn_Mobile/commit/20fbdf97e5ec1d7900244edd1fae5b236866964d)

The output looks like the following:

intent:#Intent;component=org.sana.android/.activity.AmbulanceDriverListActivity;end

That should be what needs to be used in the Procedure XML.
