### ISSUE TITLE
Synching EncouterTasks of Midwife with VHT of girls Location

### ISSUE THREAD

**Issue by donrukanga1** [UNFPAInnovation/GetIn_Mobile#40]
When Girl is mapped by Midwife, VHT of girl's Village should see her upcomingAppointment.

**Comment by ewinkler** [comment]
If the upcoming appointment is created as a Task assigned to the Midwife, this is going to be a cross Observer synch. We probably can do it if we modify the synch mechanism to query based on the 'subject' field of the task as opposed to the logged in Observer object. Local viewing on the device could be done using similar selection criteria.

**Comment by ewinkler** [comment]
There is an additional server change I am going to have to implement to make this work. Not sure if it makes sense to change this tomorrow. Concerned that the change will break the dashboard temporarily.

**Comment by donrukanga1** [comment]
Is the VHT module linked to any village? Otherwise i cnt find a way to test this
