### ISSUE TITLE
PatientList

### ISSUE THREAD

**Issue by donrukanga1** [UNFPAInnovation/GetIn_Mobile#48]
Girls list is inconsistent

**Comment by ewinkler** [comment]
Please provide additional details describing the inconsistency.

**Comment by donrukanga1** [comment]
On a closer look, i realised that the repeation of the Alphabet Letters was due to case sensitivity.
ie, The List runs from A-Z for names beginning with uppercase then begins from A-Z again for the names beginning with
 Lower case letters.
