### ISSUE TITLE
VHT list synch same as Ambulance driver list 

### ISSUE THREAD

**Issue by ewinkler** [UNFPAInnovation/GetIn_Mobile#49]
If this is referring to the the synch that is executed in the VHTListActivity the problem is simply the Uri being used to invoke the background synch.

However, there is no notion of a "VHT" specific object in the data model. Both VHT's and Midwive's are considered Observer records but differ in the "role" assigned to them. Basically the VHT Activities and fragments on the client are redundant with the Observer activities and fragments. The upshot of that is the synch should get invoked using the Observer.CONTENT_URI with the role="vht" query parameter. We can discuss further at Wednesday's meeting or assign it to someone in the meantime. If either @donrukanga1 or @galimwavu have time during the day Wednesday, please take a look. Thanks.

**Comment by galimwavu** [comment]
Hello Eric. I have implemented it with the VHT activities and fragments. may be on Friday we will discuss about it. thanks. Though the VHT part is not implemented at the server side. I stand to be corrected

**Comment by ewinkler** [comment]
Thanks @galimwavu. The VHTs aren't implemented as a separate model in the database. They are just treated as Observers with role="vht". On the client side, they should get synched with the Observer accounts as had been implemented. To pull them up in the UI, you should just need to query the Observer table and include the "role", etc. We can discuss more on Friday.

**Comment by ewinkler** [comment]
The server is sending the VHT first and last names which are probably more intuitive than displaying the "username"-we really should not be displaying the "username" here anyway for security purposes anyway.
