### ISSUE TITLE
VHT calling Midwife functionality

### ISSUE THREAD

**Issue by donrukanga1** [UNFPAInnovation/GetIn_Mobile#50]
In the workflow, the VHT should be able to call the midwife using the closed user group. Should be the same as the View VHT functionality in the MIdwife flavor.

**Comment by ewinkler** [comment]
Since the synch is working and issue #49 is "Ready To Test", can we start testing this one adequately? If not what are we missing in terms of functionality.

**Comment by donrukanga1** [comment]
We need a button in the VHT module where she can call the Miodwife assigned to her

**Comment by ewinkler** [comment]
Moving the last comment by @donrukanga1 to a new issue. Otherwise, can we close this?

**Comment by galimwavu** [comment]
worked on
