### ISSUE TITLE
Appointment form is executed while editing the patient details

### ISSUE THREAD

**Issue by donrukanga1** [UNFPAInnovation/GetIn_Mobile#51]
When the midwife is editting/updating the girl's details , the appointment form is executed after and yet it shouldnt.
It should only be executed during mapping.
Is there a way we can stop it from executing during updating?

**Comment by donrukanga1** [comment]
Workflow.
For New Patient:(Click Map girl button)
Execute mapping form + Appointment Note
For Existing Patient.(Click View/Edit Girls Button-->Select Girl--> Select Update)
Execute mapping form only (with existing girls info).
Appointment Note shouldnt be executed.

To record medical info:
Select-->View/Edit All Girls-->Select Girl-->Select Update--> Select Appointment Note

**Comment by ewinkler** [comment]
Thanks @donrukanga1
