### ISSUE TITLE
Ambulance Driver List Location showing "ambulance driver location"

### ISSUE THREAD

**Issue by ewinkler** [UNFPAInnovation/GetIn_Mobile#61]
Looks like the projection used for the query does not include the "location" column. It should be added to the projection or remove the TextView that displays the default "ambulance driver location" value if not needed.

**Comment by galimwavu** [comment]
I removed it from the projection because on the server django dashboard it wasn't catered for.

**Comment by ewinkler** [comment]
The "ambulance driver location" still appears in the layout.
![image](https://cloud.githubusercontent.com/assets/6970486/24461366/db0d5286-146e-11e7-8cc0-e9cb1449e611.png)

**Comment by galimwavu** [comment]
Hello Eric, is that after updating in the latest repo? anyways let me cross checking but I remember pushing the edited code

**Comment by galimwavu** [comment]
Please check it out now. it should be fine now

**Comment by donrukanga1** [comment]
@galimwavu  its still showing

**Comment by galimwavu** [comment]
@donrukanga1 did you clone the latest repo? I changed it when Eric raised the issue. Please I have double checked the files in repo master and the location field is commented out.

**Comment by donrukanga1** [comment]
Yes

**Comment by ewinkler** [comment]
Still showing.
![image](https://cloud.githubusercontent.com/assets/6970486/24728037/4a789d08-1a26-11e7-9555-38a480cc95f3.png)
