### ISSUE TITLE
Drop down list for Parishes, sub counties and villages on dashboard

### ISSUE THREAD

**Issue by donrukanga1** [UNFPAInnovation/GetIn_Mobile#64]
We want to avoid typing errors that could make syncing the patient with the VHT and Midwife difficult.

In the workflow of the dashboard, its after the DHO clicks add VHT or Midwife or Ambulance driber

**Comment by ewinkler** [comment]
Moved to https://github.com/UNFPAInnovation/GetIn_Dashboard/issues/1
