### ISSUE TITLE
Grouping Completed Tasks below Assigned Tasks

### ISSUE THREAD

**Issue by donrukanga1** [UNFPAInnovation/GetIn_Mobile#67]
This could help the VhT better followup girls

**Comment by ewinkler** [comment]
Should just need to add order by to query(...) call-i.e. "status ASC, due_on ASC" or something similar.

**Comment by donrukanga1** [comment]
Where do we add this?

**Comment by donrukanga1** [comment]
`public class EncounterTasksHelper extends TableHelper<EncounterTask>{

    static final SimpleDateFormat sdf = new SimpleDateFormat(IModel.DATE_FORMAT, 
			Locale.US);
	public static final String SELECT_COMPOUND = "SELECT"
		+ "encountertask._id AS encountertask_id,"
		+ "encountertask.uuid AS encountertask_uuid,"
		+ "encountertask.due_on AS due_on ,"
		+ "encountertask.modified AS modified,"`
should it be attached before this?

**Comment by ewinkler** [comment]
That is a join I was working on at one point to make the query more efficient. The change needs to go in the onCreateLoader() method. I am going to assign to myself and take a first pass.

**Comment by ewinkler** [comment]
Order by has been updated.The assigned layout looks a little off when viewed next to the completed.
![image](https://cloud.githubusercontent.com/assets/6970486/24726754/78af9974-1a21-11e7-9092-c6ec268a9ad1.png)

**Comment by ewinkler** [comment]
Also, we should probably just remove the procedure title. Somewhat meaningless for our purposes and, since we don't load the Midwife appointment form in the VHT version, is always null.

**Comment by ewinkler** [comment]
Disregard last comment. Fixed after I pulled.
