### ISSUE TITLE
Clicking the mapping form/Vht Follow up note returns back to the main menu

### ISSUE THREAD

**Issue by donrukanga1** [UNFPAInnovation/GetIn_Mobile#68]
This in the girls' list--> Update --> Mapping form
                                                        Vht short form

**Comment by donrukanga1** [comment]
This was happening on my phone. However , its ok on the emulator

**Comment by ewinkler** [comment]
What were the Android versions running on your phone and the emulator you tested on?

**Comment by donrukanga1** [comment]
Emulator is android 6.0
The phone is android 5.1

**Comment by ewinkler** [comment]
Did you happen to have the midwife version installed on the phone?
