### ISSUE TITLE
Sync Taking close to aminute

### ISSUE THREAD

**Issue by donrukanga1** [UNFPAInnovation/GetIn_Mobile#69]
Sync for girls' names takes upto a minute. Could it be made quicker?

**Comment by ewinkler** [comment]
Is this just that the foreground notification is lingering-i.e. issue #60, or is it that the fetch is in fact taking that long to complete?

**Comment by donrukanga1** [comment]
I think its the fetch. When I refreshed the list by removing all of them,
 I wasn't successful to fetch them again

**Comment by ewinkler** [comment]
1. We should probably lose the delete
2. I added the large heap = True to the application attributes in the manifest which should help.
Try it again and see if it has improved.
