### ISSUE TITLE
Updating mapping form doesn't bring girl's details

### ISSUE THREAD

**Issue by donrukanga1** [UNFPAInnovation/GetIn_Mobile#73]
VHT module.
Button Update should bring girls records from the db

**Comment by ewinkler** [comment]
The value of the uuid in the mapping form in the VHT flavor doesn't match the value the MainActivity uses to check whether it is a registration form. 

Unless I am mistaken, the mapping form should be the same in both flavors. I updated the value in the vht version to reflect that.
