### ISSUE TITLE
Should we have a "phone" icon on the Call Ambulance item in the appointment/follow up notes?

### ISSUE THREAD

**Issue by ewinkler** [UNFPAInnovation/GetIn_Mobile#77]
Shows as a button with no text or graphic. Might not be clear to the end users.

**Comment by donrukanga1** [comment]
That would make sense. Where would it be changed from?

**Comment by ewinkler** [comment]
The button layout is set in the ProcedureElement.getActions(Context) method. Since we aren't using any other foreground elements with action attributes we could either set the text explictly or switch to an image button with the call drawable resource.

**Comment by ewinkler** [comment]
@donrukanga1 I assigned this one to you but let me know if that is problematic. Thanks.

**Comment by donrukanga1** [comment]
Didnt quite get how it will be done

**Comment by ewinkler** [comment]
The getActions(Context) method essentially instatiates the View classes which are added when it is called. Changing the layout could be done by either:

1. Adding something like "Call Ambulance" text to the Button.
2. Changing the Button to an ImageButton and adding the "call" image drawable and possibly "Call Ambulance" text.

The existing code should then handle adding the layout to the UI.

**Comment by donrukanga1** [comment]
solved
