### ISSUE TITLE
CAll VHT button in MIdwife release possible cause of crash

### ISSUE THREAD

**Issue by donrukanga1** [UNFPAInnovation/GetIn_Mobile#81]
Clicking the Call VHT button and returning alone , then pressing any other button is crashing the app

**Comment by ewinkler** [comment]
Test again. Found a couple of issues in the client that I think fixed the problem. Also I found some issues with some of the older observer records on the dev server where the created field was null. Was causing some problems on the client so I fixed the records on the dev server.
