### ISSUE TITLE
ANC generation code needs to be monitored for bug

### ISSUE THREAD

**Issue by donrukanga1** [UNFPAInnovation/GetIn_Mobile#95]
![getinadmin](https://user-images.githubusercontent.com/16231167/38743973-3848f01c-3f49-11e8-91c5-7675e4213e85.PNG)

**Comment by ewinkler** [comment]
ANC Visit was changed to be recorded in the Follow up/appointment note forms and is no longer included with the Patient object record. Hence it is defaulting to a zero time. We can drop the field/column on the server side since it is not recorded in the Patient table. This isn't a bug.
